# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-25 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_verdict', models.BooleanField()),
                ('yes_votes', models.IntegerField()),
                ('no_votes', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date retrieved')),
            ],
        ),
    ]
